### PR TITLE
Enable release SBOMs gathering

### PR DESCRIPTION
**Pull request by gtema**
- add release metadata (all artifacts included in SCS release)
- gather sbom for every container of the SCS release
- publish SBOMs to dependencytrack

Signed-off-by: Artem Goncharov <artem.goncharov@gmail.com>

### CODE REVIEW

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Review by g2tema — APPROVED** [review]

**Comment by garloff** [comment]
Well, I can not foresee what precisely zuul is doing upon seeing this playbooks.
I understand the intention though:
* We want to have a list of all images (or other artifacts) that we pull in from container registries
* These have a version and a hash value
* We can use tools to look inside them to understand what is included in them

This is most of what we need for an SBOM.
As per discussion today, we want to use these for several purposes:
(1) Use them to discover potential vulnerabilities. We need to add a way that when reviewing them, we can record our findings and annotate the results, so we don't need to do the same work over and over again.
(2) Use them to hand our downstream users an SBOM. This will increasingly become a standard requirement.
(3) More advanced downstream users (operators) will want to have the capability to create their own SBOM on the fly. Our implementation thus would server as a reference implementation they can clone and enhance to their needs (and hopefully contribute back things of common interest).

**Review by garloff — APPROVED** [review]
I have no deep expertise to predict what exactly zuul will make with these playbooks.
I do not see anything that does not look harmless, so the worst case is probably that it just won't succeed ...
I understand the intention and fully approve of it.

**Comment by gtema** [comment]
> I have no deep expertise to predict what exactly zuul will make with these playbooks. I do not see anything that does not look harmless, so the worst case is probably that it just won't succeed ... I understand the intention and fully approve of it.

You can see that zuul jobs passed and the data you can see now in dependencytrack are exactly the ones uploaded by zuul (also here you can see job logs).

One thing to  check (but can be also added incrementally later) - are all the artifacts listed here or something is missed?
- I am not aware of which useful containers are there for centralApi
- keycloak image is not there yet (but we are not sure in it as of now anyway)
- health monitor image is missing (I am not sure we've built it ever)
- ...

**Comment by gtema** [comment]
Merging it. Further additions can be done afterwards

**Pull request merged**
